name: Build and Deploy iOS App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install briefcase

      - name: Build iOS app
        run: |
          briefcase create iOS
          briefcase build iOS

      - name: Package iOS app
        run: |
          briefcase package iOS

      - name: Upload .ipa as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ios-ipa
          path: ios/build/ios/xcode/build/Release-iphoneos/*.ipa
