name: Build and Deploy iOS App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install briefcase
    - name: Build iOS app
      run: |
        briefcase build iOS
    - name: Deploy iOS app
      run: |
        briefcase package iOS
